import SwiftUI

struct ContentView: View {
    @StateObject private var onboardingViewModel = OnboardingViewModel()
    @State private var showingOnboarding = true

    var body: some View {
        Group {
            if showingOnboarding {
                OnboardingView()
                    .environmentObject(onboardingViewModel)
            } else if let workoutPlan = onboardingViewModel.generatedPlan {
                WorkoutPlanView(workoutPlan: workoutPlan)
            } else {
                WelcomeView(showOnboarding: $showingOnboarding)
            }
        }
        .onChange(of: onboardingViewModel.generatedPlan) { plan in
            if plan != nil {
                showingOnboarding = false
            }
        }
    }
}

struct WelcomeView: View {
    @Binding var showOnboarding: Bool

    var body: some View {
        NavigationView {
            VStack(spacing: 30) {
                Spacer()

                VStack(spacing: 20) {
                    Image(systemName: "figure.run")
                        .font(.system(size: 80))
                        .foregroundColor(.blue)

                    Text("WorkoutPlanner AI")
                        .font(.largeTitle)
                        .fontWeight(.bold)

                    Text("Get personalized workout plans generated by AI based on your preferences and available equipment")
                        .font(.body)
                        .foregroundColor(.secondary)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal)
                }

                Spacer()

                VStack(spacing: 15) {
                    Button("Create My Workout Plan") {
                        showOnboarding = true
                    }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.large)

                    Text("Takes less than 2 minutes")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .padding(.bottom, 50)
            }
            .navigationTitle("")
            .navigationBarHidden(true)
        }
    }
}

#Preview {
    ContentView()
}