-- TASK: Create body_metrics table for tracking user body composition over time
CREATE TABLE body_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    weight_kg DECIMAL(5,2) NOT NULL,
    body_fat_pct DECIMAL(4,1),
    muscle_mass_kg DECIMAL(5,2),
    waist_cm DECIMAL(5,1),
    recorded_at DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_body_metrics_user_id
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_body_metrics_user_id ON body_metrics(user_id);
CREATE INDEX idx_body_metrics_user_recorded_at ON body_metrics(user_id, recorded_at);

COMMENT ON TABLE body_metrics IS 'Tracks body composition metrics per user over time';
COMMENT ON COLUMN body_metrics.user_id IS 'References the user ID from the users table';
COMMENT ON COLUMN body_metrics.weight_kg IS 'Body weight in kilograms';
COMMENT ON COLUMN body_metrics.body_fat_pct IS 'Body fat percentage';
COMMENT ON COLUMN body_metrics.muscle_mass_kg IS 'Muscle mass in kilograms';
COMMENT ON COLUMN body_metrics.waist_cm IS 'Waist circumference in centimeters';
COMMENT ON COLUMN body_metrics.recorded_at IS 'Date the measurement was taken';
