-- TASK: Create plan_usage_tracker table for billing period plan generation limits
CREATE TABLE plan_usage_tracker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    billing_period_start DATE NOT NULL,
    billing_period_end DATE NOT NULL,
    plans_generated INT NOT NULL DEFAULT 0,
    max_plans_allowed INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_plan_usage_tracker_user_id
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_plan_usage_tracker_user_id ON plan_usage_tracker(user_id);
CREATE INDEX idx_plan_usage_tracker_user_period ON plan_usage_tracker(user_id, billing_period_start);

COMMENT ON TABLE plan_usage_tracker IS 'Tracks plan generation usage per user per billing period';
COMMENT ON COLUMN plan_usage_tracker.user_id IS 'References the user ID from the users table';
COMMENT ON COLUMN plan_usage_tracker.billing_period_start IS 'Start date of the billing period';
COMMENT ON COLUMN plan_usage_tracker.billing_period_end IS 'End date of the billing period';
COMMENT ON COLUMN plan_usage_tracker.plans_generated IS 'Number of plans generated in this billing period';
COMMENT ON COLUMN plan_usage_tracker.max_plans_allowed IS 'Maximum plans allowed for this billing period';
