-- TASK-BILLING-001: Webhook event log table for auditing RevenueCat webhook events
CREATE TABLE webhook_event_log (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               VARCHAR(255) REFERENCES users(id) ON DELETE SET NULL,
    provider_customer_id  VARCHAR(255),
    event_type            VARCHAR(100) NOT NULL,
    event_payload         TEXT NOT NULL,
    processed_successfully BOOLEAN NOT NULL DEFAULT FALSE,
    error_message         TEXT,
    received_at           TIMESTAMP NOT NULL
);

CREATE INDEX idx_webhook_event_log_user_id ON webhook_event_log(user_id);
CREATE INDEX idx_webhook_event_log_event_type ON webhook_event_log(event_type);
CREATE INDEX idx_webhook_event_log_received_at ON webhook_event_log(received_at);
CREATE INDEX idx_webhook_event_log_provider_customer_id ON webhook_event_log(provider_customer_id);
